In [117]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from bokeh.plotting import figure, show
import warnings
warnings.simplefilter('ignore')

## 데이터 전처리
- #### 컬럼정리
- #### 결측치처리
- #### 데이터 타입 처리
- #### 범주형 인코딩

In [118]:
data = pd.read_csv('../dataset/appleAppData.csv')
data

,App_Id,App_Name,AppStore_Url,Primary_Genre,Content_Rating,Size_Bytes,Required_IOS_Version,Released,Updated,Version,...,Currency,Free,DeveloperId,Developer,Developer_Url,Developer_Website,Average_User_Rating,Reviews,Current_Version_Score,Current_Version_Reviews
0,com.hkbu.arc.apaper,A+ Paper Guide,https://apps.apple.com/us/app/a-paper-guide/id...,Education,4+,21993472.0,8.0,2017-09-28T03:02:41Z,2018-12-21T21:30:36Z,1.1.2,...,USD,True,1375410542,HKBU ARC,https://apps.apple.com/us/developer/hkbu-arc/i...,NaN,0.00000,0,0.00000,0
1,com.dmitriev.abooks,A-Books,https://apps.apple.com/us/app/a-books/id103157...,Book,4+,13135872.0,10.0,2015-08-31T19:31:32Z,2019-07-23T20:31:09Z,1.3,...,USD,True,1031572001,Roman Dmitriev,https://apps.apple.com/us/developer/roman-dmit...,NaN,5.00000,1,5.00000,1
2,no.terp.abooks,A-books,https://apps.apple.com/us/app/a-books/id145702...,Book,4+,21943296.0,9.0,2021-04-14T07:00:00Z,2021-05-30T21:08:54Z,1.3.1,...,USD,True,1457024163,Terp AS,https://apps.apple.com/us/developer/terp-as/id...,NaN,0.00000,0,0.00000,0
3,fr.antoinettefleur.Book1,A-F Book #1,https://apps.apple.com/us/app/a-f-book-1/id500...,Book,4+,81851392.0,8.0,2012-02-10T03:40:07Z,2019-10-29T12:40:37Z,1.2,...,USD,False,439568839,i-editeur.com,https://apps.apple.com/us/developer/i-editeur-...,NaN,0.00000,0,0.00000,0
4,com.imonstersoft.azdictionaryios,A-Z Synonyms Dictionary,https://apps.apple.com/us/app/a-z-synonyms-dic...,Reference,4+,64692224.0,9.0,2020-12-16T08:00:00Z,2020-12-18T21:36:11Z,1.0.1,...,USD,True,656731821,Ngov chiheang,https://apps.apple.com/us/developer/ngov-chihe...,http://imonstersoft.com,0.00000,0,0.00000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1230371,com.ledtech.sadblock,Sесurity АdBlосkеr,https://apps.apple.com/us/app/s%D0%B5%D1%81uri...,Utilities,4+,16666624.0,13.0,2020-07-07T07:00:00Z,2020-07-10T00:48:50Z,1.0.1,...,USD,True,1522287989,LED-TECHNOLOGIES,https://apps.apple.com/us/developer/led-techno...,NaN,3.91608,143,3.91608,143
1230372,com.securex.vpn,SесurеХ VРN - Wifi Proxy,https://apps.apple.com/us/app/s%D0%B5%D1%81ur%...,Utilities,4+,39016448.0,9.0,2019-02-12T10:10:13Z,2020-10-21T23:25:15Z,1.1,...,USD,True,1492288123,Trust VPN Ltd.,https://apps.apple.com/us/developer/trust-vpn-...,https://securexvpn.com/,4.82733,1500,4.82733,1500
1230373,com.beelab.SoTayXayDung,Sổ tay Xây dựng,https://apps.apple.com/us/app/s%E1%BB%95-tay-x...,Utilities,4+,17223680.0,9.0,2018-10-17T04:22:41Z,2018-10-17T04:22:41Z,1.0,...,USD,True,1438594214,Luu Minh,https://apps.apple.com/us/developer/luu-minh/i...,http://bee-labs.github.io,4.00000,1,4.00000,1
1230374,com.icc.sttb,Sổ tay đảng viên Thái Bình,https://apps.apple.com/us/app/s%E1%BB%95-tay-%...,Utilities,4+,56716288.0,10.0,2021-02-20T08:00:00Z,2021-10-02T22:00:19Z,1.2.5,...,USD,True,1515469508,Thái Bình,https://apps.apple.com/us/developer/th%C3%A1i-...,https://aisoftech.vn,0.00000,0,0.00000,0
1230375,com.vnptlonganios.sodiemthongminh,Sổ Điểm Thông Minh,https://apps.apple.com/us/app/s%E1%BB%95-%C4%9...,Utilities,4+,85135360.0,8.0,2018-06-05T07:45:41Z,2019-05-21T22:03:17Z,1.9,...,USD,True,1350355912,Pham Thanh Vo,https://apps.apple.com/us/developer/pham-thanh...,NaN,0.00000,0,0.00000,0

In [119]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1230376 entries, 0 to 1230375
Data columns (total 21 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   App_Id                   1230376 non-null  object
 1   App_Name                 1230375 non-null  object
 2   AppStore_Url             1230376 non-null  object
 3   Primary_Genre            1230376 non-null  object
 4   Content_Rating           1230376 non-null  object
 5   Size_Bytes               1230152 non-null  float64
 6   Required_IOS_Version     1230376 non-null  object
 7   Released                 1230373 non-null  object
 8   Updated                  1230376 non-null  object
 9   Version                  1230376 non-null  object
 10  Price                    1229886 non-null  float64
 11  Currency                 1230376 non-null  object
 12  Free                     1230376 non-null  bool
 13  DeveloperId              1230376 non-null  int64
 14  Developer                1230376 non-null  object
 15  Developer_Url            1229267 non-null  object
 16  Developer_Website        586388 non-null   object
 17  Average_User_Rating      1230376 non-null  float64
 18  Reviews                  1230376 non-null  int64
 19  Current_Version_Score    1230376 non-null  float64
 20  Current_Version_Reviews  1230376 non-null  int64
dtypes: bool(1), float64(4), int64(3), object(13)
memory usage: 188.9+ MB

### 평가가 이루어지지 않은 데이터 삭제

In [120]:
# 총 데이터 - 1230376 
# 평점 0 - 684320
# 리뷰 0 - 684320
# 평점리뷰 모두 '0' - 684320
data = data[(data['Reviews'] != 0) & (data['Average_User_Rating'] != 0.0)]
data

,App_Id,App_Name,AppStore_Url,Primary_Genre,Content_Rating,Size_Bytes,Required_IOS_Version,Released,Updated,Version,...,Currency,Free,DeveloperId,Developer,Developer_Url,Developer_Website,Average_User_Rating,Reviews,Current_Version_Score,Current_Version_Reviews
1,com.dmitriev.abooks,A-Books,https://apps.apple.com/us/app/a-books/id103157...,Book,4+,13135872.0,10.0,2015-08-31T19:31:32Z,2019-07-23T20:31:09Z,1.3,...,USD,True,1031572001,Roman Dmitriev,https://apps.apple.com/us/developer/roman-dmit...,NaN,5.00000,1,5.00000,1
10,com.pitashi.audiojoy.aacompanionfree,AA Audio Companion for Alcoholics Anonymous,https://apps.apple.com/us/app/aa-audio-compani...,Book,17+,26133504.0,8.0,2017-04-19T13:24:42Z,2017-08-24T00:29:56Z,3.6.1,...,USD,True,1253337114,Kepler47 Software Inc.,https://apps.apple.com/us/developer/kepler47-s...,NaN,4.78132,1285,4.78132,1285
11,com.goodbarber.bigbookfree,AA Big Book (Unofficial),https://apps.apple.com/us/app/aa-big-book-unof...,Book,17+,63112192.0,9.0,2015-05-12T07:45:22Z,2021-09-18T18:55:21Z,2.2.16,...,USD,True,1473747716,Sobriety Soft LLC,https://apps.apple.com/us/developer/sobriety-s...,http://sobrietysoft.org,4.78902,1839,4.78902,1839
12,com.laltrello.aabigbookandmore,AA Big Book and More,https://apps.apple.com/us/app/aa-big-book-and-...,Lifestyle,4+,3095552.0,9.0,2012-04-02T11:01:26Z,2017-04-11T03:25:00Z,4.0,...,USD,False,354615800,Rob Laltrello,https://apps.apple.com/us/developer/rob-laltre...,NaN,4.67354,242,4.67354,242
13,com.aabigbook.appstore,AA Big Book App - Unofficial,https://apps.apple.com/us/app/aa-big-book-app-...,Book,17+,2094080.0,8.0,2015-12-19T00:41:11Z,2018-10-17T20:01:47Z,1.4.2,...,USD,False,295775659,Dean Huff,https://apps.apple.com/us/developer/dean-huff/...,http://aabigbookapp.com,3.09524,21,3.09524,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1230360,br.com.zellar.chansey.chamaaqui,São Judas - Chama Aqui!,https://apps.apple.com/us/app/s%C3%A3o-judas-c...,Utilities,4+,41021440.0,9.0,2018-09-18T15:56:24Z,2020-03-12T17:23:09Z,2.0.2,...,USD,True,1378665404,Zellar,https://apps.apple.com/us/developer/zellar/id1...,NaN,5.00000,1,5.00000,1
1230368,is.siminn.app.service,Síminn,https://apps.apple.com/us/app/s%C3%ADminn/id58...,Utilities,4+,96898048.0,10.0,2012-11-30T17:40:52Z,2021-09-27T10:08:01Z,2.0.16,...,USD,True,509495492,Síminn,https://apps.apple.com/us/developer/s%C3%ADmin...,https://www.siminn.is/forsida/simi/meirimogule...,4.42856,7,4.42856,7
1230371,com.ledtech.sadblock,Sесurity АdBlосkеr,https://apps.apple.com/us/app/s%D0%B5%D1%81uri...,Utilities,4+,16666624.0,13.0,2020-07-07T07:00:00Z,2020-07-10T00:48:50Z,1.0.1,...,USD,True,1522287989,LED-TECHNOLOGIES,https://apps.apple.com/us/developer/led-techno...,NaN,3.91608,143,3.91608,143
1230372,com.securex.vpn,SесurеХ VРN - Wifi Proxy,https://apps.apple.com/us/app/s%D0%B5%D1%81ur%...,Utilities,4+,39016448.0,9.0,2019-02-12T10:10:13Z,2020-10-21T23:25:15Z,1.1,...,USD,True,1492288123,Trust VPN Ltd.,https://apps.apple.com/us/developer/trust-vpn-...,https://securexvpn.com/,4.82733,1500,4.82733,1500
1230373,com.beelab.SoTayXayDung,Sổ tay Xây dựng,https://apps.apple.com/us/app/s%E1%BB%95-tay-x...,Utilities,4+,17223680.0,9.0,2018-10-17T04:22:41Z,2018-10-17T04:22:41Z,1.0,...,USD,True,1438594214,Luu Minh,https://apps.apple.com/us/developer/luu-minh/i...,http://bee-labs.github.io,4.00000,1,4.00000,1

In [121]:
# 불필요 컬럼 제거
cols = ['App_Name', 'App_Id', 'AppStore_Url', 'Released', 'Updated', 'Required_IOS_Version', 'Version', 'DeveloperId', 'Developer', 'Developer_Url', 'Developer_Website', 'Current_Version_Score', 'Current_Version_Reviews', 'Currency']
data.drop(cols, axis=1, inplace=True)

In [122]:
data

,Primary_Genre,Content_Rating,Size_Bytes,Price,Free,Average_User_Rating,Reviews
1,Book,4+,13135872.0,0.00,True,5.00000,1
10,Book,17+,26133504.0,0.00,True,4.78132,1285
11,Book,17+,63112192.0,0.00,True,4.78902,1839
12,Lifestyle,4+,3095552.0,1.99,False,4.67354,242
13,Book,17+,2094080.0,0.99,False,3.09524,21
...,...,...,...,...,...,...,...
1230360,Utilities,4+,41021440.0,0.00,True,5.00000,1
1230368,Utilities,4+,96898048.0,0.00,True,4.42856,7
1230371,Utilities,4+,16666624.0,0.00,True,3.91608,143
1230372,Utilities,4+,39016448.0,0.00,True,4.82733,1500
1230373,Utilities,4+,17223680.0,0.00,True,4.00000,1

In [123]:
data.rename(columns={'Primary_Genre' : 'Category',
                      'Content_Rating' : 'Available_Age',
                        'Size_Bytes' : 'Size',
                        'Average_User_Rating' : 'Rating'}, inplace=True)
data

          Category Available_Age        Size  Price   Free   Rating  Reviews
1             Book            4+  13135872.0   0.00   True  5.00000        1
10            Book           17+  26133504.0   0.00   True  4.78132     1285
11            Book           17+  63112192.0   0.00   True  4.78902     1839
12       Lifestyle            4+   3095552.0   1.99  False  4.67354      242
13            Book           17+   2094080.0   0.99  False  3.09524       21
...            ...           ...         ...    ...    ...      ...      ...
1230360  Utilities            4+  41021440.0   0.00   True  5.00000        1
1230368  Utilities            4+  96898048.0   0.00   True  4.42856        7
1230371  Utilities            4+  16666624.0   0.00   True  3.91608      143
1230372  Utilities            4+  39016448.0   0.00   True  4.82733     1500
1230373  Utilities            4+  17223680.0   0.00   True  4.00000        1

[546056 rows x 7 columns]

In [124]:
# null값확인
data.isnull().sum()

Category           0
Available_Age      0
Size             139
Price            139
Free               0
Rating             0
Reviews            0
dtype: int64

In [125]:
# null값 채우기 - 평균값(trend반영X)
data['Price'].fillna(data['Price'].mean(), inplace=True)
data['Size'].fillna(data['Size'].mean(), inplace=True)

In [126]:
data.isnull().sum()

Category         0
Available_Age    0
Size             0
Price            0
Free             0
Rating           0
Reviews          0
dtype: int64

In [127]:
# 사이즈 MB화
data['Size'] = ((data['Size'] / (1024*1024)).round()).astype(int)

In [128]:
# 가격 정수화, 평점 반올림
data['Price'] = data['Price'].round().astype(int)
data['Rating'] = data['Rating'].round(2)

In [129]:
data['Category'].nunique(), data['Category'].unique()

(26,
 array(['Book', 'Lifestyle', 'Reference', 'Health & Fitness', 'Games',
        'Education', 'Medical', 'Utilities', 'News', 'Productivity',
        'Entertainment', 'Music', 'Shopping', 'Photo & Video', 'Travel',
        'Business', 'Food & Drink', 'Social Networking', 'Sports',
        'Navigation', 'Finance', 'Stickers', 'Magazines & Newspapers',
        'Weather', 'Graphics & Design', 'Developer Tools'], dtype=object))

In [130]:
''' 
이용가능 연령대 - Integer Encoding
everyone - 0
kid - 1
children - 2
teens - 3
adults - 4
'''
data['Available_Age'] = data['Available_Age'].replace('4+', 1)
data['Available_Age'] = data['Available_Age'].replace('9+', 2)
data['Available_Age'] = data['Available_Age'].replace('12+', 3)
data['Available_Age'] = data['Available_Age'].replace('17+', 4)
data['Available_Age'] = data['Available_Age'].replace('Not yet rated', 0)
data['Available_Age'] = data['Available_Age'].astype(int)

In [131]:
data

          Category  Available_Age  Size  Price   Free  Rating  Reviews
1             Book              1    13      0   True    5.00        1
10            Book              4    25      0   True    4.78     1285
11            Book              4    60      0   True    4.79     1839
12       Lifestyle              1     3      2  False    4.67      242
13            Book              4     2      1  False    3.10       21
...            ...            ...   ...    ...    ...     ...      ...
1230360  Utilities              1    39      0   True    5.00        1
1230368  Utilities              1    92      0   True    4.43        7
1230371  Utilities              1    16      0   True    3.92      143
1230372  Utilities              1    37      0   True    4.83     1500
1230373  Utilities              1    16      0   True    4.00        1

[546056 rows x 7 columns]

---

### Integer Encoding

In [132]:
cate_list = data['Category'].unique()
cate_list

array(['Book', 'Lifestyle', 'Reference', 'Health & Fitness', 'Games',
       'Education', 'Medical', 'Utilities', 'News', 'Productivity',
       'Entertainment', 'Music', 'Shopping', 'Photo & Video', 'Travel',
       'Business', 'Food & Drink', 'Social Networking', 'Sports',
       'Navigation', 'Finance', 'Stickers', 'Magazines & Newspapers',
       'Weather', 'Graphics & Design', 'Developer Tools'], dtype=object)

In [133]:
cate_dict = {}
for index in range(len(cate_list)):
    cate_dict[cate_list[index]] = index

data['Cate_Int'] = data['Category'].map(cate_dict).astype(int)
data.head()

     Category  Available_Age  Size  Price   Free  Rating  Reviews  Cate_Int
1        Book              1    13      0   True    5.00        1         0
10       Book              4    25      0   True    4.78     1285         0
11       Book              4    60      0   True    4.79     1839         0
12  Lifestyle              1     3      2  False    4.67      242         1
13       Book              4     2      1  False    3.10       21         0

### One Hot Encoding

In [134]:
data_dum = pd.get_dummies(data, columns=['Category'])
data_dum.columns

Index(['Available_Age', 'Size', 'Price', 'Free', 'Rating', 'Reviews',
       'Cate_Int', 'Category_Book', 'Category_Business',
       'Category_Developer Tools', 'Category_Education',
       'Category_Entertainment', 'Category_Finance', 'Category_Food & Drink',
       'Category_Games', 'Category_Graphics & Design',
       'Category_Health & Fitness', 'Category_Lifestyle',
       'Category_Magazines & Newspapers', 'Category_Medical', 'Category_Music',
       'Category_Navigation', 'Category_News', 'Category_Photo & Video',
       'Category_Productivity', 'Category_Reference', 'Category_Shopping',
       'Category_Social Networking', 'Category_Sports', 'Category_Stickers',
       'Category_Travel', 'Category_Utilities', 'Category_Weather'],
      dtype='object')

In [135]:
data_dum

,Available_Age,Size,Price,Free,Rating,Reviews,Cate_Int,Category_Book,Category_Business,Category_Developer Tools,...,Category_Photo & Video,Category_Productivity,Category_Reference,Category_Shopping,Category_Social Networking,Category_Sports,Category_Stickers,Category_Travel,Category_Utilities,Category_Weather
1,1,13,0,True,5.00,1,0,True,False,False,...,False,False,False,False,False,False,False,False,False,False
10,4,25,0,True,4.78,1285,0,True,False,False,...,False,False,False,False,False,False,False,False,False,False
11,4,60,0,True,4.79,1839,0,True,False,False,...,False,False,False,False,False,False,False,False,False,False
12,1,3,2,False,4.67,242,1,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13,4,2,1,False,3.10,21,0,True,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1230360,1,39,0,True,5.00,1,7,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1230368,1,92,0,True,4.43,7,7,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1230371,1,16,0,True,3.92,143,7,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1230372,1,37,0,True,4.83,1500,7,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1230373,1,16,0,True,4.00,1,7,False,False,False,...,False,False,False,False,False,False,False,False,True,False

### Binary Encoding

In [136]:
import category_encoders as ce
# BinaryEncoder 인스턴스 생성
encoder = ce.BinaryEncoder(cols=['Category'], return_df=True)

In [137]:
encoder

BinaryEncoder(cols=['Category'])

In [138]:
data = encoder.fit_transform(data)
data

,Category_0,Category_1,Category_2,Category_3,Category_4,Available_Age,Size,Price,Free,Rating,Reviews,Cate_Int
1,0,0,0,0,1,1,13,0,True,5.00,1,0
10,0,0,0,0,1,4,25,0,True,4.78,1285,0
11,0,0,0,0,1,4,60,0,True,4.79,1839,0
12,0,0,0,1,0,1,3,2,False,4.67,242,1
13,0,0,0,0,1,4,2,1,False,3.10,21,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1230360,0,1,0,0,0,1,39,0,True,5.00,1,7
1230368,0,1,0,0,0,1,92,0,True,4.43,7,7
1230371,0,1,0,0,0,1,16,0,True,3.92,143,7
1230372,0,1,0,0,0,1,37,0,True,4.83,1500,7
1230373,0,1,0,0,0,1,16,0,True,4.00,1,7

In [139]:
# 정수인코딩 데이터, 바이너리인코딩 데이터
data_int = data.drop(['Category_0','Category_1','Category_2','Category_3','Category_4'], axis=1)
data_bin = data.drop('Cate_Int', axis=1)
# data_dum

In [140]:
data_int

         Available_Age  Size  Price   Free  Rating  Reviews  Cate_Int
1                    1    13      0   True    5.00        1         0
10                   4    25      0   True    4.78     1285         0
11                   4    60      0   True    4.79     1839         0
12                   1     3      2  False    4.67      242         1
13                   4     2      1  False    3.10       21         0
...                ...   ...    ...    ...     ...      ...       ...
1230360              1    39      0   True    5.00        1         7
1230368              1    92      0   True    4.43        7         7
1230371              1    16      0   True    3.92      143         7
1230372              1    37      0   True    4.83     1500         7
1230373              1    16      0   True    4.00        1         7

[546056 rows x 7 columns]

In [141]:
data_bin

,Category_0,Category_1,Category_2,Category_3,Category_4,Available_Age,Size,Price,Free,Rating,Reviews
1,0,0,0,0,1,1,13,0,True,5.00,1
10,0,0,0,0,1,4,25,0,True,4.78,1285
11,0,0,0,0,1,4,60,0,True,4.79,1839
12,0,0,0,1,0,1,3,2,False,4.67,242
13,0,0,0,0,1,4,2,1,False,3.10,21
...,...,...,...,...,...,...,...,...,...,...,...
1230360,0,1,0,0,0,1,39,0,True,5.00,1
1230368,0,1,0,0,0,1,92,0,True,4.43,7
1230371,0,1,0,0,0,1,16,0,True,3.92,143
1230372,0,1,0,0,0,1,37,0,True,4.83,1500
1230373,0,1,0,0,0,1,16,0,True,4.00,1

In [142]:
data_int.to_csv('../dataset/app_int.csv')
data_bin.to_csv('../dataset/app_bin.csv')
data_dum.to_csv('../dataset/app_dum.csv')

In [48]:
x=[1,2,3,4,5]
y=[6,7,8,9,10]

In [49]:
# p = figure(title='Simple_line_example', x_axis_label='x', y_axis_label='y')

# p.line(x,y,legend_label='Temp', line_width=2)
# show(p)